SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_VENDEDORES;
SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME, IDADE FROM TABELA_DE_CLIENTES;

SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DO CLIENTE] FROM TABELA_DE_CLIENTES TDC;
SELECT TDC.IDADE, TDC.BAIRRO FROM TABELA_DE_CLIENTES TDC;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE < 20;

SELECT* FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'PET';
SELECT* FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = '243083';

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '1995/10/25';

SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO >= 'LAPA';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA' AND TAMANHO = '350 ML';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA' OR TAMANHO = '1,5 LITROS';
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'MANGA' AND TAMANHO = '350 ML');
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA' OR SABOR = 'UVA' OR SABOR = 'MELANCIA';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('MANGA', 'UVA', 'MELANCIA');
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('MANGA', 'UVA', 'MELANCIA') AND TAMANHO = '1 LITRO';

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('RIO DE JANEIRO', 'SAO PAULO') AND IDADE > = 20 AND IDADE <=25;
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('RIO DE JANEIRO', 'SAO PAULO') AND IDADE BETWEEN 20 AND 25;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE 'MORANGO%';

SELECT * FROM TABELA_DE_CLIENTES WHERE NOME LIKE '%SILVA%';

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS;














