SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_VENDEDORES;
SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME, IDADE FROM TABELA_DE_CLIENTES;

SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DO CLIENTE] FROM TABELA_DE_CLIENTES TDC;
SELECT TDC.IDADE, TDC.BAIRRO FROM TABELA_DE_CLIENTES TDC;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE < 20;

SELECT* FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'PET';
SELECT* FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = '243083';

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '1995/10/25';

SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO >= 'LAPA';















